version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: produccion_jamar
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  app:
    image: persistencia
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/produccion_jamar?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8081"

    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
